spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_template
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: debug